### TRAINING CONFIGURATIONS ###
mode: training

dataset_dir: /home/manuelli/spartan_grasp/data_volume/dexnet/datasets/dexnet2-detection/3dnet_kit_detection_08_11_17/grasps/tensors
output_dir: /home/manuelli/spartan_grasp/data_volume/dexnet/trained_models
model_dir: /home/manuelli/spartan_grasp/data_volume/dexnet/models/GQ (from RSS 2017 paper)


# general optimization parameters
train_batch_size: 512
val_batch_size: 256
num_epochs: 25
eval_frequency: 10000
save_frequency: 10000
vis_frequency: 10000
log_frequency: 1
show_filters: 0

queue_capacity: 500
queue_sleep: 0.01

data_split_mode: image_wise
train_pct: 0.8
total_pct: 1.0
eval_total_train_error: 0

loss: sparse
optimizer: momentum
train_l2_regularizer: 0.0005
base_lr: 0.01
decay_step_multiplier: 0.2
decay_rate: 0.95
momentum_rate: 0.9
max_training_examples_per_load: 512
fine_tune: 0
update_fc_only: 1
update_conv0_only: 0
reinit_fc3: 0
reinit_fc4: 0
reinit_fc5: 0

image_mode: depth_tf_table
training_mode: classification
preproc_mode: none
input_data_mode: tf_image
num_tensor_channels: 1

num_random_files: 100
target_metric_name: robust_ferrari_canny
metric_thresh: 0.002

# denoising / synthetic data params
multiplicative_denoising: 1
gamma_shape: 1000.0
symmetrize: 1
morphological: 0
morph_open_rate: 0.25
morph_poisson_mean: 1.5
image_dropout: 0
image_dropout_rate: 0.25
dropout_poisson_mean: 1.0
dropout_radius_shape: 3.0
dropout_radius_scale: 1.0
gradient_dropout: 0
gradient_dropout_rate: 0.1
gradient_dropout_sigma: 0.5
gradient_dropout_shape: 15
gradient_dropout_scale: 0.001
gaussian_process_denoising: 1
gaussian_process_rate: 0.5
gaussian_process_scaling_factor: 4.0
gaussian_process_sigma: 0.005
border_distortion: 0
border_grad_sigma: 1.0
border_grad_thresh: 0.075
border_poisson_mean: 5.0
border_radius_shape: 5
border_radius_scale: 0.4
background_denoising: 0
background_rate: 0.25
background_min_depth: 0.0
background_max_depth: 0.65


drop_fc3: 0
fc3_drop_rate: 0
drop_fc4: 0
fc4_drop_rate: 0
debug: 0
debug_num_files: 300

gqcnn_config:
  im_height: 32
  im_width: 32
  im_channels: 1
  input_data_mode: tf_image
  batch_size: 256
  architecture:
    conv1_1:
      filt_dim: 7
      num_filt: 64
      pool_size: 1
      pool_stride: 1
      norm: 0
      norm_type: local_response
    conv1_2:
      filt_dim: 5
      num_filt: 64
      pool_size: 2
      pool_stride: 2
      norm: 1
      norm_type: local_response
    conv2_1:
      filt_dim: 3
      num_filt: 64
      pool_size: 1
      pool_stride: 1
      norm: 0
      norm_type: local_response
    conv2_2:
      filt_dim: 3
      num_filt: 64
      pool_size: 1
      pool_stride: 1
      norm: 1
      norm_type: local_response
    pc1:
      out_size: 16
    pc2:
      out_size: 0
    fc3:
      out_size: 1024
    fc4:
      out_size: 1024
    fc5:
      out_size: 2
  radius: 2
  alpha: 2.0e-05
  beta: 0.75
  bias: 1.0